---
parser: babel-eslint
env:
  browser: true
extends: [airbnb, plugin:react/recommended]
plugins: [import, react]
settings:
  import/resolver:
    node: {}
    webpack:
      config: webpack.config.js

rules:
  array-callback-return: 1
  camelcase: off
  class-methods-use-this: 1
  comma-dangle: [1, only-multiline]
  consistent-return: 0
  default-case: 0
  dot-notation: 1
  eqeqeq: 1
  guard-for-in: 1
  import/imports-first: 1
  import/no-mutable-exports: 0
  jsx-a11y/anchor-is-valid: [warn, {"aspects": [invalidHref]}]
  jsx-a11y/href-no-hash: 'off'
  jsx-a11y/label-has-for: 0
  jsx-a11y/no-static-element-interactions: 1
  max-len: [0, 80, 2, {"ignoreComments": true}]
  no-bitwise: 1
  no-class-assign: 0
  no-cond-assign: [2, except-parens]
  no-continue: 1
  no-else-return: 0
  no-extend-native: 1
  no-fallthrough: 'off'
  no-param-reassign: 0
  no-plusplus: 1
  no-prototype-builtins: 1
  no-restricted-syntax: 1
  no-unused-expressions: 1
  no-unused-vars: [1, {"args": none, "vars": local}]
  no-use-before-define: 1
  prefer-const: 1
  quote-props: [1, consistent-as-needed]
  quotes: 0
  radix: 0
  react/forbid-prop-types: 1
  space-infix-ops: 0
  no-underscore-dangle: [2, {"allowAfterThis": true}]
  vars-on-top: 0
  object-curly-newline: [2, {"consistent": true}]
  function-paren-newline: [2, "consistent"]
  react/no-array-index-key: 1
  jsx-a11y/click-events-have-key-events: 0
  jsx-a11y/no-noninteractive-element-interactions: 1
  prefer-promise-reject-errors: 1
  react/jsx-key: 1
  indent: 1
  import/no-unresolved: 1
  import/extensions: 1
  react/destructuring-assignment: 1
  react/jsx-one-expression-per-line: 1
  react/jsx-wrap-multilines: 1
  operator-linebreak: [1, after]
  lines-between-class-members: 1
  react/no-access-state-in-setstate: 1
  implicit-arrow-linebreak: 1
  jsx-a11y/label-has-associated-control: 1
  jsx-a11y/control-has-associated-label: 0
  arrow-parens: [2, "always"]
