#!/usr/bin/env python

import sys

def main():
    import argparse

    parser = argparse.ArgumentParser(description='Cesium web frontend')
    parser.add_argument('--port', type=int, default=4000,
                        help='Port number (default 4000)')
    parser.add_argument('--host', type=str, default='127.0.0.1',
                        help='Address to listen on (default 127.0.0.1)')
    parser.add_argument('--debug', action='store_true',
                        help='Enable debugging (default: False)')
    parser.add_argument('--disable-auth', action='store_true',
                        help='Disable user authentication')
    parser.add_argument('--db-init', action='store_true',
                        help='Initialize the database')
    parser.add_argument('--force', action='store_true',
                        help='When used with db-init, overwrite existing db')
    args = parser.parse_args()


    if args.db_init:
        from cesium_app.models import drop_tables, create_tables
        if args.force:
            print("Dropping tables...")
            drop_tables()

        print("Re-creating tables, if non-existent...")
        create_tables()

        print("Database setup complete.")

        sys.exit(0)

    from cesium_app.flask_server import app

    if args.debug:
        app.config['DEBUG'] = True
        app.config['WTF_CSRF_ENABLED'] = False

    print("Launching server on %s:%s" % (args.host, args.port))
    app.run(port=args.port, host=args.host, threaded=True)


if __name__ == "__main__":
    main()
