#!/usr/bin/env python

import sys

def main():
    import argparse

    parser = argparse.ArgumentParser(description='mock cesium w/ react web frontend')
    parser.add_argument('--port', type=int, default=4000,
                        help='Port number (default 4000)')
    parser.add_argument('--host', type=str, default='127.0.0.1',
                        help='Address to listen on (default 127.0.0.1)')
    parser.add_argument('--debug', action='store_true',
                        help='Enable debugging (default: False)')
    parser.add_argument('--disable-auth', action='store_true',
                        help='Disable user authentication')
    parser.add_argument('--db-init', action='store_true',
                        help='Initialize the database')
    parser.add_argument('--force', action='store_true',
                        help='When used with db-init, overwrite existing db')
    args = parser.parse_args()


    if args.db_init:
        from flask_server import db_init
        db_init(force=args.force)
        sys.exit(0)

    from flask_server import app

    if args.debug:
        app.config['DEBUG'] = True
        app.config['WTF_CSRF_ENABLED'] = False

    print("Launching server on %s:%s" % (args.host, args.port))
    app.run(port=args.port, host=args.host, threaded=True)


if __name__ == "__main__":
    main()
