app:
    secret-key: abc01234  # This secret key can be any random string of
                          # characters.
                          #
                          # You should re-generate this for your application
                          # using:
                          #
                          # base64.b64encode(os.urandom(50)).decode('ascii')
paths:
    # Note below that defined variables can be reused in subsequent
    # definitions.

    data_path: './data'
    models_folder: './data/models'
    features_folder: './data/extracted_features'
    predictions_folder: './data/predictions'
    ts_data_folder: './data/ts_data'
    upload_folder: './data/uploads'
    custom_feature_script_folder: './data/uploads/custom_feature_scripts'

database:
    database: cesium
    host: localhost
    port: 5432
    user: cesium
    password:

server:
    # From https://console.developers.google.com/
    #
    # - Create Client ID
    # - Javascript origins: https://localhost:5000
    # - Authorized redirect URLs: http://localhost:5000/complete/google-oauth2/
    #
    # You need to have Google+ API enabled; it takes a few minutes to activate.

    auth:
        debug_login: True
        google_oauth2_key:
        google_oauth2_secret:
